name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: todo-app
    steps:
      -
        name: Checkout the repo
        uses: actions/checkout@v2
      -
        name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ECR_URL }}
          username: ${{ secrets.AWS_ECR_USERNAME }}
          password: ${{ secrets.AWS_ECR_PASSWORD }}
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AWS_ECR_URL}}/todo-app:latest
